package View;

import Controllers.ConnectionDB;
import Controllers.NoteDAO;
import Models.Note;
import Models.User;
import Controllers.UserDAO;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class MainPageView extends javax.swing.JFrame {
    
    private static User loggedUser; //aquí guardaré el loggedUser sacado del Login

    private DefaultListModel<String> noteListModel = new DefaultListModel<>(); //Declaro un modelo de tipo Note (por defecto es String)
    
    private static boolean editing = false;

    public MainPageView(User loggedUser) {
        
        initComponents();
        
        // guardo el objeto loggedUser recibido de LoginView en el atributo creado "private User loggedUser;"
        this.loggedUser = loggedUser;
                
        setupErrorLabelAndFocus();
        
        jList_noteList.setModel(noteListModel);
                
        pullNotesFromDB(); //cogemos las notas del usuario de la BDD

        this.setLocationRelativeTo(null); //centra la ventana al iniciarse
        
        //SWITCH de PANELES nothing, new, etc.
        //Damos nombre a cada panel para ir cambiando de vista
        parentCardPanel.add(pnl_nothing, "nothing");
        parentCardPanel.add(pnl_new, "new");
        parentCardPanel.add(pnl_preview, "preview");
        parentCardPanel.add(pnl_edit, "edit");
        
        //muestro texto si no hay notas
        if(!noteListModel.isEmpty()){
            lbl_arrow.setVisible(false);
            lbl_noNotes.setVisible(false);
        }
 
        //LISTA DE NOTAS
        // Le decimos a la lista que escuche cuando se selecciona un elemento
        jList_noteList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                // Evitamos que se ejecute el código dos veces (por seguridad)
                if (!e.getValueIsAdjusting()) {
                    // Obtenemos el valor (título de la nota) que el usuario seleccionó
                    String selectedTitle = jList_noteList.getSelectedValue();
                    if(editing == true){
                        JOptionPane.showMessageDialog(null, "You must save before leaving");
                        return;
                    }

                    // muestro el panel PREVIEW
                    if (selectedTitle != null) {
                        CardLayout cl = (CardLayout)(parentCardPanel.getLayout());
                        cl.show(parentCardPanel, "preview");
                        
                        lbl_prevTitle.setText(selectedTitle);
                        
                        //cambio propiedades para que no se pueda editar el JTextArea
                        Color backgroundColor = new Color(70,73,75);
                        txt_prevContent.setEditable(false); // No editable
                        txt_prevContent.setFocusable(false); // No recibe foco
                        txt_prevContent.setOpaque(true); // Fondo transparente
                        txt_prevContent.setLineWrap(true); // Salto de línea automático
                        txt_prevContent.setWrapStyleWord(true); // No corta palabras
                        txt_prevContent.setBorder(BorderFactory.createEmptyBorder()); // Sin borde
                        txt_prevContent.setBackground(backgroundColor); // pongo el color del fondo del panel
                        txt_prevContent.setHighlighter(null); // Elimina resaltado de selección si no quieres que se pueda seleccionar texto
                        
                        String content = NoteDAO.getContent(selectedTitle, loggedUser.getId());
                        // El content.replace("\n", "<br>") reemplaza los \n por <br> porque un jLabel no lee \n.
                        // Como hay que usar html para que funcione <br>, lo abrimos y cerramos.
                        if(content.startsWith("<html>")){
                            txt_prevContent.setText(content.replace("<html>", "").replace("<br>","\n").replace("</html>", ""));
                        }else{
                            txt_prevContent.setText(content);
                        }
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_princinpal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_imageUser = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_noteList = new javax.swing.JList<>();
        parentCardPanel = new javax.swing.JPanel();
        pnl_nothing = new javax.swing.JPanel();
        lbl_arrow = new javax.swing.JLabel();
        lbl_noNotes = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_new = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_saveNote = new javax.swing.JButton();
        txt_title = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_content = new javax.swing.JTextArea();
        lbl_errorText = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnl_preview = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_prevTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_export = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_prevContent = new javax.swing.JTextArea();
        pnl_edit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_editTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_editContent = new javax.swing.JTextArea();
        btn_saveEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ISOCT3_IV50", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Notes");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo mosaico v3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        btn_imageUser.setBackground(new java.awt.Color(70, 73, 75));
        btn_imageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/photo user v3_1.png"))); // NOI18N
        btn_imageUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageUserActionPerformed(evt);
            }
        });

        btn_new.setBackground(new java.awt.Color(78, 130, 255));
        btn_new.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_new.setText("New ");
        btn_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(70, 73, 75));

        jScrollPane1.setViewportView(jList_noteList);

        parentCardPanel.setLayout(new java.awt.CardLayout());

        pnl_nothing.setBackground(new java.awt.Color(70, 73, 75));

        lbl_arrow.setFont(new java.awt.Font("ISOCT3_IV50", 1, 18)); // NOI18N
        lbl_arrow.setForeground(new java.awt.Color(255, 255, 255));
        lbl_arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_arrow.setText("<---------------");
        lbl_arrow.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_arrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_noNotes.setFont(new java.awt.Font("ISOCT3_IV50", 1, 18)); // NOI18N
        lbl_noNotes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_noNotes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_noNotes.setText("<html>You don't have any<br>Note yet");
        lbl_noNotes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("ISOCT3_IV50", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DeskNotes");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnl_nothingLayout = new javax.swing.GroupLayout(pnl_nothing);
        pnl_nothing.setLayout(pnl_nothingLayout);
        pnl_nothingLayout.setHorizontalGroup(
            pnl_nothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nothingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_nothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_noNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_arrow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_nothingLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        pnl_nothingLayout.setVerticalGroup(
            pnl_nothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_nothingLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_noNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        parentCardPanel.add(pnl_nothing, "card2");

        pnl_new.setBackground(new java.awt.Color(70, 73, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Title");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Content");

        btn_saveNote.setBackground(new java.awt.Color(78, 130, 255));
        btn_saveNote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_saveNote.setForeground(new java.awt.Color(255, 255, 255));
        btn_saveNote.setText("Save Note");
        btn_saveNote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_saveNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveNoteActionPerformed(evt);
            }
        });

        txt_content.setColumns(20);
        txt_content.setRows(5);
        jScrollPane2.setViewportView(txt_content);

        lbl_errorText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_errorText.setForeground(new java.awt.Color(255, 0, 0));
        lbl_errorText.setText("You must fill all the gaps");

        jLabel11.setFont(new java.awt.Font("ISOCT3_IV50", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("New Note");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnl_newLayout = new javax.swing.GroupLayout(pnl_new);
        pnl_new.setLayout(pnl_newLayout);
        pnl_newLayout.setHorizontalGroup(
            pnl_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_newLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(txt_title))
                    .addGroup(pnl_newLayout.createSequentialGroup()
                        .addComponent(lbl_errorText)
                        .addGap(61, 61, 61)
                        .addComponent(btn_saveNote)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_newLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(193, 193, 193))
        );
        pnl_newLayout.setVerticalGroup(
            pnl_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_newLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_saveNote)
                    .addComponent(lbl_errorText))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        parentCardPanel.add(pnl_new, "card3");

        pnl_preview.setBackground(new java.awt.Color(70, 73, 75));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Title");

        lbl_prevTitle.setText("Titulo de la nota seleccionada");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Content");

        btn_edit.setBackground(new java.awt.Color(78, 130, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(78, 130, 255));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_export.setBackground(new java.awt.Color(78, 130, 255));
        btn_export.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_export.setForeground(new java.awt.Color(255, 255, 255));
        btn_export.setText("Export");
        btn_export.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(null);

        txt_prevContent.setEditable(false);
        txt_prevContent.setBackground(new java.awt.Color(70, 73, 75));
        txt_prevContent.setColumns(20);
        txt_prevContent.setRows(5);
        txt_prevContent.setBorder(null);
        jScrollPane4.setViewportView(txt_prevContent);

        javax.swing.GroupLayout pnl_previewLayout = new javax.swing.GroupLayout(pnl_preview);
        pnl_preview.setLayout(pnl_previewLayout);
        pnl_previewLayout.setHorizontalGroup(
            pnl_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_previewLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_previewLayout.createSequentialGroup()
                        .addComponent(btn_export)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(btn_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete))
                    .addComponent(lbl_prevTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_previewLayout.setVerticalGroup(
            pnl_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_previewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_prevTitle)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_export))
                .addGap(26, 26, 26))
        );

        parentCardPanel.add(pnl_preview, "card4");

        pnl_edit.setBackground(new java.awt.Color(70, 73, 75));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Title");

        lbl_editTitle.setText("Titulo de la nota seleccionada");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Content");

        txt_editContent.setColumns(20);
        txt_editContent.setRows(5);
        jScrollPane3.setViewportView(txt_editContent);

        btn_saveEdit.setBackground(new java.awt.Color(78, 130, 255));
        btn_saveEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_saveEdit.setForeground(new java.awt.Color(255, 255, 255));
        btn_saveEdit.setText("Save");
        btn_saveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_editLayout = new javax.swing.GroupLayout(pnl_edit);
        pnl_edit.setLayout(pnl_editLayout);
        pnl_editLayout.setHorizontalGroup(
            pnl_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_editLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_editLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_editLayout.createSequentialGroup()
                        .addGroup(pnl_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_editLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbl_editTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_editLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_saveEdit)
                .addGap(62, 62, 62))
        );
        pnl_editLayout.setVerticalGroup(
            pnl_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_editLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_editTitle)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_saveEdit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        parentCardPanel.add(pnl_edit, "card5");

        javax.swing.GroupLayout pnl_princinpalLayout = new javax.swing.GroupLayout(pnl_princinpal);
        pnl_princinpal.setLayout(pnl_princinpalLayout);
        pnl_princinpalLayout.setHorizontalGroup(
            pnl_princinpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_princinpalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_princinpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_princinpalLayout.createSequentialGroup()
                        .addGroup(pnl_princinpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_princinpalLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnl_princinpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_imageUser))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parentCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnl_princinpalLayout.setVerticalGroup(
            pnl_princinpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_princinpalLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_princinpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_princinpalLayout.createSequentialGroup()
                        .addComponent(btn_imageUser)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_new))
                    .addComponent(parentCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_princinpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_princinpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pullNotesFromDB(){
        String sql = "SELECT title FROM table_note WHERE userId=?";
        try(Connection conn = ConnectionDB.connectWithDB()){ //nos conectamos a la BDR
            PreparedStatement stmt = conn.prepareStatement(sql); //transformamos instrucción para que lo pueda leer la bdd
            stmt.setInt(1, loggedUser.getId());
            ResultSet rs = stmt.executeQuery(); //ejecutamos SELECT
            
            while(rs.next()){
                String title = rs.getString("title");
                noteListModel.addElement(title);
            }

        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void btn_imageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageUserActionPerformed
        JOptionPane.showMessageDialog(null, loggedUser.toString(), "USER DATA", -1);
    }//GEN-LAST:event_btn_imageUserActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        if(editing == true){
            JOptionPane.showMessageDialog(null, "You must save before leaving");
            return;
        }
        // muestro el pnl_new
        CardLayout cl = (CardLayout)(parentCardPanel.getLayout());
        cl.show(parentCardPanel, "new");
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_saveNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveNoteActionPerformed
        String title = txt_title.getText();
        String content = txt_content.getText();
        int userId = UserDAO.searchUserId(loggedUser);
        
        if(userId == 0){
            JOptionPane.showMessageDialog(null, "❌ id User not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(title.isEmpty() || content.isEmpty()){
            lbl_errorText.setForeground(Color.RED);
            return;
        }
        boolean repeatedTitle = NoteDAO.repeatedTitle(title, loggedUser.getId());
        if(repeatedTitle == true){
            JOptionPane.showMessageDialog(null, "❌ Repeated title", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Creamos la Note si encontramos el user, están los 2 campos rellenados, y no se repite el title
        Note newNote = new Note(userId, title, content);
        
        // guardo la nota en la BDD
        NoteDAO.saveNote(newNote);
        
        // guardo la nota en el modelo
        noteListModel.addElement(newNote.getTitle()); //en el toString solo tengo el título, por lo tanto solo se verá el título
        
        //vacío los campos
        txt_title.setText(null);
        txt_content.setText(null);
        
        // me voy al panel nothing
        CardLayout cl = (CardLayout) (parentCardPanel.getLayout());
        cl.show(parentCardPanel, "nothing");
        JOptionPane.showMessageDialog(null, "New Note saved successfully");
        
        // quito el texto porque si guardo algo, nunca estará vacío
        lbl_arrow.setVisible(false);
        lbl_noNotes.setVisible(false);
    }//GEN-LAST:event_btn_saveNoteActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int chose = JOptionPane.showConfirmDialog(null, "Are you sure?", "Delete Note", JOptionPane.YES_NO_OPTION);
        String title = lbl_prevTitle.getText();
        
        if(chose == JOptionPane.YES_OPTION){
            int idNote = NoteDAO.getIdfromTitle(title);
            if (idNote != -1){
                NoteDAO.deleteNote(title, idNote);
                noteListModel.removeElement(title);

                CardLayout cl = (CardLayout) (parentCardPanel.getLayout());
                cl.show(parentCardPanel, "nothing");
                JOptionPane.showMessageDialog(null, "Note deleted successfully");
                
                if(noteListModel.isEmpty()){
                lbl_arrow.setVisible(true);
                lbl_noNotes.setVisible(true);
        }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        CardLayout cl = (CardLayout) (parentCardPanel.getLayout());
        cl.show(parentCardPanel, "edit");
        editing = true; //entramos en "modo edición"
        lbl_editTitle.setText(lbl_prevTitle.getText());
        
        String htmlText = txt_prevContent.getText();
        String plainText = htmlText.replace("<html>", "")
                                   .replace("</html>", "")
                                   .replace("<br>", "\n");
        
        txt_editContent.setText(plainText);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_saveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveEditActionPerformed
        String title = lbl_editTitle.getText();
        String plainTextContent = txt_editContent.getText();
        String content = "<html>" + plainTextContent.replace("\n", "<br>") + "</html>";
        
        if(plainTextContent.equals(txt_prevContent.getText())){
            JOptionPane.showMessageDialog(null, "You haven't done any changes", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        NoteDAO.saveEditNote(title, content);
        
        editing = false;
        JOptionPane.showMessageDialog(null, "Note edited successfully");
        CardLayout cl = (CardLayout) (parentCardPanel.getLayout());
        cl.show(parentCardPanel, "nothing");
        
        if(!noteListModel.isEmpty()){
            lbl_arrow.setVisible(false);
            lbl_noNotes.setVisible(false);
        }
    }//GEN-LAST:event_btn_saveEditActionPerformed

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed
        String title = lbl_prevTitle.getText();
        String htmlContent = txt_prevContent.getText();
        String content = htmlContent.replace("<html>", "")
                                    .replace("<br>", "\n")
                                    .replace("</html>", "\n");
        
        JFileChooser fileChooser = new JFileChooser(); //creo un exportador de archivos
        fileChooser.setDialogTitle("Save as txt"); //cambio el título del fileChooser (arriba izq)
        fileChooser.setSelectedFile(new File(title + ".txt")); //nombre predeterminado del archivo
        
        //Guardo la selección del user. Si ha sido guardar o cancelar
        int userSelection = fileChooser.showSaveDialog(null);
        
        if (userSelection == JFileChooser.APPROVE_OPTION){ //habiendo pulsado guardar
            File fileToSave = fileChooser.getSelectedFile(); //obtengo el archivo que el usuario seleccionó (con la ruta completa)
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))){
                writer.write(title + "\n\n" + content);
                JOptionPane.showMessageDialog(null, "Note saved successfully");
            }catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error saving the Note", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_exportActionPerformed

    // método para ocultar o mostrar el errorText
    private void setupErrorLabelAndFocus() {
        // 1. Al iniciar invisible (color fondo)
        lbl_errorText.setForeground(pnl_new.getBackground());

        // 3. Cuando se hace foco en cualquiera de los campos, oculta el mensaje
        FocusAdapter focusAdapter = new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                lbl_errorText.setForeground(pnl_new.getBackground());
            }
        };
        txt_title.addFocusListener(focusAdapter);
        txt_content.addFocusListener(focusAdapter);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        // para aplicar FlatLaf:
        FlatDarkLaf.setup();
        MainPageView mainPage = new MainPageView(loggedUser);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainPage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_export;
    private javax.swing.JButton btn_imageUser;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_saveEdit;
    private javax.swing.JButton btn_saveNote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_noteList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_arrow;
    private javax.swing.JLabel lbl_editTitle;
    private javax.swing.JLabel lbl_errorText;
    private javax.swing.JLabel lbl_noNotes;
    private javax.swing.JLabel lbl_prevTitle;
    private javax.swing.JPanel parentCardPanel;
    private javax.swing.JPanel pnl_edit;
    private javax.swing.JPanel pnl_new;
    private javax.swing.JPanel pnl_nothing;
    private javax.swing.JPanel pnl_preview;
    private javax.swing.JPanel pnl_princinpal;
    private javax.swing.JTextArea txt_content;
    private javax.swing.JTextArea txt_editContent;
    private javax.swing.JTextArea txt_prevContent;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
